In [1]:
# Load NumPy package
import numpy as np

In [2]:
# Create array1
array1 = np.array([[1, 2], [3, 4]])
array1

array([[1, 2],
       [3, 4]])

In [3]:
# Create array2
array2 = np.array([[5, 6], [7, 8]])
array2

array([[5, 6],
       [7, 8]])

In [4]:
# Add array1 and array2
array1 + array2

array([[ 6,  8],
       [10, 12]])

In [5]:
# Subtract array1 and array2
array1 - array2

array([[-4, -4],
       [-4, -4]])

In [6]:
# Multiply array1 and array2
array1 * array2

array([[ 5, 12],
       [21, 32]])

In [7]:
# Divide array1 by array2
array1 / array2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [8]:
# Find square root of array 2 elements
np.sqrt(array2)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [9]:
# Find the dot product of rows of array1 and columns of array2
np.dot(array1, array2)

array([[19, 22],
       [43, 50]])